chore: uses `publicSettingsForApp` endpoint to retrieve app settings
vtex-apps/minicart-freeshipping-bar pull request #21
Opened 2023-02-17 17:49 UTC by emersonlaurentino

This PR uses the [new endpoint at apps-graphql](https://github.com/vtex/apps-graphql/blob/v3.x/graphql/schema.graphql#L46) to retrieve public settings from apps.

2023-02-17 18:20 UTC, danzanzini approved these changes

2023-02-21 14:13 UTC, lariciamota requested changes

2023-02-21 14:13 UTC, lariciamota commented on manifest.json
>    "settingsSchema": {
It'll be necessary to add the access public property
```suggestion
  "settingsSchema": {
  "access": "public",
```

2023-02-23 21:33 UTC, diegoleone approved these changes

2023-02-24 14:27 UTC, lariciamota approved these changes

2023-02-24 14:28 UTC, merged